# Generated by Django 2.2.6 on 2019-10-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
