# Generated by Django 2.2.6 on 2019-12-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20191031_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
